# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Check pull request

on:
  pull_request:
    branches:
      - "main"

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: "yarn"

      - name: 🧶 Setup yarn
        run: corepack enable

      - name: 📦 Install Dependencies
        run: |
          yarn install --immutable

      - name: 🔥 generate:components
        run: yarn generate:components

      - name: 💣 build
        run: yarn build
