# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Check pull request

on:
  pull_request:
    branches:
      - main

jobs:
  check_pull_request:
    name: PR Stats
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - uses: actions/checkout@v4      

      - name: 🔥 Setup corepack
        run: corepack enable

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: 📦 Install Dependencies
        run: |
          pnpm --version && pnpm install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔥 Run generate:icons
        run: pnpm run generate:icons

      - name: 💣 Run build
        run: pnpm run build
