# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Check pull request

on:
  pull_request:
    branches:
      - main

env:
  PNPM_VERSION: 8.10.0

jobs:
  check_pull_request:
    name: PR Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: 🔥 Installing pnpm
        run: |
          corepack enable
          corepack prepare pnpm@${{ env.PNPM_VERSION }} --activate

      - name: 📦 Install dependencies
        run: |
          pnpm install --no-frozen-lockfile

      - name: 🔥 generate:icons
        run: pnpm run generate:icons

      - name: 💣 build
        run: pnpm run build
