# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release SvelteSimpleIcons

on:
  push:
    branches:
      - main
  release:
    types: [created]

env:
  PNPM_VERSION: 8.10.0

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: 🔥 Installing pnpm
        run: |
          corepack enable
          corepack prepare pnpm@${{ env.PNPM_VERSION }} --activate

      - name: 📦 Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔥 generate:icons
        run: pnpm run generate:icons

      - name: 💣 build
        run: pnpm run build

      # - name: Delete tags
      #   run: |
      #     git tag | xargs git tag -d

      - name: Create Release Pull Request or Publish to GitHub Packages 📦
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: "ci(Release): version icons-pack/react-simple-icons"
          title: "ci(Release): version icons-pack/react-simple-icons"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
